export const FETCH_CONTACT_START = 'FETCH_CONTACT_START'
export const FETCH_CONTACT_SUCCESS = 'FETCH_CONTACT_SUCCESS'
export const FETCH_CONTACT_ERROR = 'FETCH_CONTACT_ERROR'

export const FETCH_HOME_PAGE_START = 'FETCH_HOME_PAGE_START'
export const FETCH_HOME_PAGE_SUCCESS = 'FETCH_HOME_PAGE_SUCCESS'
export const FETCH_HOME_PAGE_ERROR = 'FETCH_HOME_PAGE_ERROR'

export const FETCH_STATISTIC_START = 'FETCH_STATISTIC_START'
export const FETCH_STATISTIC_SUCCESS = 'FETCH_STATISTIC_SUCCESS'
export const FETCH_STATISTIC_ERROR = 'FETCH_STATISTIC_ERROR'

export const FETCH_DOCTORS_START = 'FETCH_DOCTORS_START'
export const FETCH_DOCTORS_SUCCESS = 'FETCH_DOCTORS_SUCCESS'
export const FETCH_DOCTORS_ERROR = 'FETCH_DOCTORS_ERROR'
