# Generated by Django 4.0.2 on 2022-03-16 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalContactInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=30, verbose_name='Номер телефона')),
                ('email', models.CharField(max_length=255, verbose_name='Email')),
                ('location', models.CharField(max_length=255, verbose_name='Местоположение клиники')),
                ('img_user', models.ImageField(upload_to='user_information/<django.db.models.fields.CharField>')),
                ('avatar_user', models.ImageField(upload_to='user_information/avatar/<django.db.models.fields.CharField>')),
            ],
            options={
                'verbose_name': 'Контактная информация',
                'verbose_name_plural': 'Контактная информация',
            },
        ),
        migrations.CreateModel(
            name='MedicalDirections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(max_length=60, verbose_name='Медицинское направление')),
            ],
            options={
                'verbose_name': 'Медицинское направление',
                'verbose_name_plural': 'Медицинские направления',
            },
        ),
    ]
