# Generated by Django 4.0.2 on 2022-03-16 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_medicalcontactinformation_img_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slogan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slogan_header', models.CharField(max_length=255, verbose_name='Заголовок слогана')),
                ('slogan_description', models.CharField(max_length=255, verbose_name='Описание слогана')),
                ('img', models.ImageField(upload_to='slang/', verbose_name='Картинка слогана')),
            ],
            options={
                'verbose_name': 'Слоган',
                'verbose_name_plural': 'Слоганы',
            },
        ),
    ]
