# Generated by Django 4.0.2 on 2022-03-16 11:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_slogan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slogan',
            name='img',
        ),
        migrations.AddField(
            model_name='slogan',
            name='icon',
            field=models.FileField(null=True, upload_to='slang/', validators=[django.core.validators.FileExtensionValidator(['svg'])], verbose_name='Иконка'),
        ),
    ]
