# Generated by Django 4.0.2 on 2022-03-19 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_patientstatistics'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientstatistics',
            old_name='chambers_number',
            new_name='chambers_counter',
        ),
        migrations.RenameField(
            model_name='patientstatistics',
            old_name='clinics_number',
            new_name='clinics_counter',
        ),
        migrations.RenameField(
            model_name='patientstatistics',
            old_name='employees_number',
            new_name='employees_counter',
        ),
        migrations.RenameField(
            model_name='patientstatistics',
            old_name='patients_number',
            new_name='patients_counter',
        ),
    ]
