# Generated by Django 4.0.2 on 2022-03-22 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_rename_chambers_number_patientstatistics_chambers_counter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalcontactinformation',
            name='avatar_user',
            field=models.ImageField(upload_to='user_information/avatar/<django.db.models.fields.CharField>', verbose_name='Аватарка'),
        ),
    ]
