# Generated by Django 4.0.2 on 2022-03-22 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_medicalcontactinformation_avatar_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО врача')),
                ('specialization', models.CharField(max_length=255, verbose_name='Специализация')),
                ('education', models.CharField(max_length=255, verbose_name='Образование')),
                ('internship', models.CharField(max_length=255, verbose_name='Интернатура')),
                ('work_experience', models.CharField(max_length=255, verbose_name='Стаж работы')),
                ('primary_specialization', models.CharField(max_length=255, verbose_name='Первичная специализация')),
                ('additional_information', models.CharField(max_length=255, verbose_name='Дополнительная информация')),
            ],
            options={
                'verbose_name': 'Информация о доторе',
                'verbose_name_plural': 'Информация о докторах',
            },
        ),
    ]
