# Generated by Django 4.0.2 on 2022-03-22 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_doctorsinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorsDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО врача')),
                ('specialization', models.CharField(max_length=255, verbose_name='Специализация')),
                ('education', models.CharField(max_length=255, verbose_name='Образование')),
                ('internship', models.CharField(max_length=255, verbose_name='Интернатура')),
                ('work_experience', models.CharField(max_length=255, verbose_name='Стаж работы')),
                ('primary_specialization', models.CharField(max_length=255, verbose_name='Первичная специализация')),
                ('additional_information', models.CharField(max_length=255, verbose_name='Дополнительная информация')),
            ],
            options={
                'verbose_name': 'Описание доктора',
                'verbose_name_plural': 'Описание докторов',
            },
        ),
        migrations.CreateModel(
            name='InterestsDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование профессионального интереса')),
            ],
            options={
                'verbose_name': 'Наименование профессионального интереса',
                'verbose_name_plural': 'Наименование профессиональных интересов',
            },
        ),
        migrations.CreateModel(
            name='QualificationsDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование квалификации')),
            ],
            options={
                'verbose_name': 'Наименование квалификации',
                'verbose_name_plural': 'Наименование квалификаций',
            },
        ),
        migrations.DeleteModel(
            name='DoctorsInfo',
        ),
        migrations.AddField(
            model_name='doctorsdescription',
            name='needed_for_interests',
            field=models.ManyToManyField(through='mainapp.DoctorInfo', to='mainapp.InterestsDoctor'),
        ),
        migrations.AddField(
            model_name='doctorsdescription',
            name='needed_for_qualifications',
            field=models.ManyToManyField(through='mainapp.DoctorInfo', to='mainapp.QualificationsDoctor'),
        ),
        migrations.AddField(
            model_name='doctorinfo',
            name='description',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.doctorsdescription'),
        ),
        migrations.AddField(
            model_name='doctorinfo',
            name='interests',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.interestsdoctor'),
        ),
        migrations.AddField(
            model_name='doctorinfo',
            name='qualifications',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.qualificationsdoctor'),
        ),
    ]
