# Generated by Django 4.0.2 on 2022-03-22 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_doctorinfo_doctorsdescription_interestsdoctor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorsdescription',
            name='needed_for_interests',
        ),
        migrations.RemoveField(
            model_name='doctorsdescription',
            name='needed_for_qualifications',
        ),
        migrations.AddField(
            model_name='doctorsdescription',
            name='qualifications_doctor',
            field=models.ManyToManyField(blank=True, related_name='qualifications', to='mainapp.QualificationsDoctor'),
        ),
        migrations.DeleteModel(
            name='DoctorInfo',
        ),
    ]
