# Generated by Django 4.0.2 on 2022-03-22 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_remove_doctorsdescription_needed_for_interests_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorsdescription',
            name='interests_doctor',
            field=models.ManyToManyField(blank=True, related_name='interests', to='mainapp.InterestsDoctor'),
        ),
    ]
