# Generated by Django 4.0.2 on 2022-03-22 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_doctorsdescription_interests_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorsdescription',
            name='qualifications_doctor',
            field=models.ManyToManyField(blank=True, related_name='qualifications', to='mainapp.QualificationsDoctor', verbose_name='Квалификации доктора'),
        ),
    ]
