# Generated by Django 4.0.2 on 2022-03-23 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_alter_doctorsdescription_interests_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='CookingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=50)),
                ('cooking_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.cookingproduct')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.dish')),
            ],
            options={
                'verbose_name': 'Ингридиент',
                'verbose_name_plural': 'Ингридиенты',
            },
        ),
        migrations.AddField(
            model_name='cookingproduct',
            name='needed_for_dishes',
            field=models.ManyToManyField(to='mainapp.Dish'),
        ),
    ]
