# Generated by Django 4.0.2 on 2022-03-23 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_cookingproduct_dish_ingredient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interestsdoctor',
            name='id_doctor_description',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='mainapp.doctorsdescription'),
        ),
        migrations.AddField(
            model_name='qualificationsdoctor',
            name='id_doctor_description',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='mainapp.doctorsdescription'),
        ),
        migrations.RemoveField(
            model_name='doctorsdescription',
            name='interests_doctor',
        ),
        migrations.AddField(
            model_name='doctorsdescription',
            name='interests_doctor',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='mainapp.interestsdoctor'),
        ),
        migrations.RemoveField(
            model_name='doctorsdescription',
            name='qualifications_doctor',
        ),
        migrations.AddField(
            model_name='doctorsdescription',
            name='qualifications_doctor',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='mainapp.qualificationsdoctor'),
        ),
    ]
