# Generated by Django 4.0.2 on 2022-03-23 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_interestsdoctor_id_doctor_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО врача')),
            ],
            options={
                'verbose_name': 'Врач',
                'verbose_name_plural': 'Врачи',
            },
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='cooking_product',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='dish',
        ),
        migrations.RemoveField(
            model_name='doctorsdescription',
            name='interests_doctor',
        ),
        migrations.RemoveField(
            model_name='doctorsdescription',
            name='name',
        ),
        migrations.RemoveField(
            model_name='doctorsdescription',
            name='qualifications_doctor',
        ),
        migrations.DeleteModel(
            name='CookingProduct',
        ),
        migrations.DeleteModel(
            name='Dish',
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.AddField(
            model_name='doctorsdescription',
            name='id_doctor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='mainapp.doctors'),
        ),
    ]
