# Generated by Django 4.0.2 on 2022-03-23 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_doctors_remove_ingredient_cooking_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interestsdoctor',
            name='id_doctor_description',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='mainapp.doctors'),
        ),
        migrations.AlterField(
            model_name='qualificationsdoctor',
            name='id_doctor_description',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='mainapp.doctors'),
        ),
    ]
