# Generated by Django 4.0.2 on 2022-03-23 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_alter_interestsdoctor_id_doctor_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorsdescription',
            name='id_doctor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='mainapp.doctors', verbose_name='Врач'),
        ),
        migrations.AlterField(
            model_name='interestsdoctor',
            name='id_doctor_description',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='mainapp.doctors', verbose_name='Врач'),
        ),
        migrations.AlterField(
            model_name='qualificationsdoctor',
            name='id_doctor_description',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='mainapp.doctors', verbose_name='Врач'),
        ),
    ]
