# Generated by Django 4.0.2 on 2022-03-23 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_remove_medicalcontactinformation_avatar_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorsdescription',
            name='working_position',
            field=models.CharField(default='', max_length=255, verbose_name='Рабочая должность'),
        ),
        migrations.AlterField(
            model_name='doctorsdescription',
            name='avatar_user',
            field=models.ImageField(default='', upload_to='doctors/avatar/<django.db.models.fields.related.ForeignKey>', verbose_name='Аватарка'),
        ),
        migrations.AlterField(
            model_name='doctorsdescription',
            name='img_user',
            field=models.ImageField(default='', upload_to='doctors/<django.db.models.fields.related.ForeignKey>', verbose_name='Фото'),
        ),
    ]
